namespace com.ultrabit.bitheroes.fromflash;

public class GoogleGamesEvent
{
	public static string ACHIEVEMENTS_VIEW_DISMISSED = "ACHIEVEMENTS_VIEW_DISMISSED";

	public static string INCREMENT_ACHIEVEMENT_FAILED = "INCREMENT_ACHIEVEMENT_FAILED";

	public static string INCREMENT_ACHIEVEMENT_SUCCEEDED = "INCREMENT_ACHIEVEMENT_SUCCEEDED";

	public static string LEADERBOARD_VIEW_DISMISSED = "LEADERBOARD_VIEW_DISMISSED";

	public static string LOAD_ACHIEVEMENTS_FAILED = "LOAD_ACHIEVEMENTS_FAILED";

	public static string LOAD_ACHIEVEMENTS_SUCCEEDED = "LOAD_ACHIEVEMENTS_SUCCEEDED";

	public static string LOAD_AUTH_TOKEN_FAILED = "LOAD_AUTH_TOKEN_FAILED";

	public static string LOAD_AUTH_TOKEN_SUCCEEDED = "LOAD_AUTH_TOKEN_SUCCEEDED";

	public static string LOAD_LEADERBOARD_METADATA_FAILED = "LOAD_LEADERBOARD_METADATA_FAILED";

	public static string LOAD_LEADERBOARD_METADATA_SUCCEEDED = "LOAD_LEADERBOARD_METADATA_SUCCEEDED";

	public static string LOAD_SCORES_FAILED = "LOAD_SCORES_FAILED";

	public static string LOAD_SCORES_SUCCEEDED = "LOAD_SCORES_SUCCEEDED";

	public static string REVEAL_ACHIEVEMENT_FAILED = "REVEAL_ACHIEVEMENT_FAILED";

	public static string REVEAL_ACHIEVEMENT_SUCCEEDED = "REVEAL_ACHIEVEMENT_SUCCEEDED";

	public static string SET_ACHIEVEMENT_STEPS_FAILED = "SET_ACHIEVEMENT_STEPS_FAILED";

	public static string SET_ACHIEVEMENT_STEPS_SUCCEEDED = "SET_ACHIEVEMENT_STEPS_SUCCEEDED";

	public static string SIGN_IN_FAILED = "SIGN_IN_FAILED";

	public static string SIGN_IN_SUCCEEDED = "SIGN_IN_SUCCEEDED";

	public static string SIGNED_OUT = "SIGNED_OUT";

	public static string SUBMIT_SCORE_FAILED = "SUBMIT_SCORE_FAILED";

	public static string SUBMIT_SCORE_SUCCEEDED = "SUBMIT_SCORE_SUCCEEDED";

	public static string UNLOCK_ACHIEVEMENT_FAILED = "UNLOCK_ACHIEVEMENT_FAILED";

	public static string UNLOCK_ACHIEVEMENT_SUCCEEDED = "UNLOCK_ACHIEVEMENT_SUCCEEDED";
}
