public enum ISAdQualityInitError
{
	AD_QUALITY_SDK_WAS_SHUTDOWN,
	ILLEGAL_USER_ID,
	ILLEGAL_APP_KEY,
	EXCEPTION_ON_INIT,
	NO_NETWORK_CONNECTION,
	CONFIG_LOAD_TIMEOUT,
	CONNECTOR_LOAD_TIMEOUT,
	AD_NETWORK_VERSION_NOT_SUPPORTED_YET,
	AD_NETWORK_SDK_REQUIRES_NEWER_AD_QUALITY_SDK
}
